2025-03-24 15:12:19,191 INFO    MainThread:2523374 [wandb_setup.py:_flush():76] Current SDK version is 0.15.10
2025-03-24 15:12:19,191 INFO    MainThread:2523374 [wandb_setup.py:_flush():76] Configure stats pid to 2523374
2025-03-24 15:12:19,191 INFO    MainThread:2523374 [wandb_setup.py:_flush():76] Loading settings from /home/bhanu/.config/wandb/settings
2025-03-24 15:12:19,191 INFO    MainThread:2523374 [wandb_setup.py:_flush():76] Loading settings from /scratch/bhanu/cuffless_bp/Cuffless_BP_Estimation_Diffusion_Model/wandb/settings
2025-03-24 15:12:19,191 INFO    MainThread:2523374 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2025-03-24 15:12:19,191 INFO    MainThread:2523374 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2025-03-24 15:12:19,191 INFO    MainThread:2523374 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'train.py', 'program': 'train.py'}
2025-03-24 15:12:19,192 INFO    MainThread:2523374 [wandb_init.py:_log_setup():524] Logging user logs to /scratch/bhanu/cuffless_bp/Cuffless_BP_Estimation_Diffusion_Model/wandb/run-20250324_151219-INSERT ID HERE/logs/debug.log
2025-03-24 15:12:19,192 INFO    MainThread:2523374 [wandb_init.py:_log_setup():525] Logging internal logs to /scratch/bhanu/cuffless_bp/Cuffless_BP_Estimation_Diffusion_Model/wandb/run-20250324_151219-INSERT ID HERE/logs/debug-internal.log
2025-03-24 15:12:19,192 INFO    MainThread:2523374 [wandb_init.py:init():564] calling init triggers
2025-03-24 15:12:19,192 INFO    MainThread:2523374 [wandb_init.py:init():571] wandb.init called with sweep_config: {}
config: {'n_epoch': 1000, 'batch_size': 512, 'nT': 10, 'device': 'cuda', 'attention_heads': 8, 'cond_mask': 0.0, 'alpha1': 100, 'alpha2': 1, 'PATH': 'INSERT PATH HERE'}
2025-03-24 15:12:19,192 INFO    MainThread:2523374 [wandb_init.py:init():614] starting backend
2025-03-24 15:12:19,192 INFO    MainThread:2523374 [wandb_init.py:init():618] setting up manager
2025-03-24 15:12:19,197 INFO    MainThread:2523374 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-03-24 15:12:19,199 INFO    MainThread:2523374 [wandb_init.py:init():624] backend started and connected
2025-03-24 15:12:19,206 INFO    MainThread:2523374 [wandb_init.py:init():715] updated telemetry
2025-03-24 15:12:19,236 INFO    MainThread:2523374 [wandb_init.py:init():748] communicating run to backend with 90.0 second timeout
2025-03-24 15:12:19,842 ERROR   MainThread:2523374 [wandb_init.py:init():774] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2025-03-24 15:12:20,167 ERROR   MainThread:2523374 [wandb_init.py:init():1183] It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
Traceback (most recent call last):
  File "/home/bhanu/cuffless_bp/diffusion/lib64/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1165, in init
    run = wi.init()
  File "/home/bhanu/cuffless_bp/diffusion/lib64/python3.8/site-packages/wandb/sdk/wandb_init.py", line 780, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2025-03-24 15:12:21,169 WARNING MsgRouterThr:2523374 [router.py:message_loop():77] message_loop has been closed
